master:
  tag: "2.303.1-jdk11"
  overwritePlugins: true
  enableXmlConfig: true
  runAsUser: 0
  fsGroup: 0
  JCasC:
    enabled: false
    defaultConfig: false
  sidecars:
    configAutoReload:
      enabled: false
  persistence:
    enabled: true
    size: "8Gi"
  servicePort: 8080
  targetPort: 8080
  serviceType: LoadBalancer
  installPlugins:
    - sonar:2.13.1
    - deploy:1.16
    - workflow-aggregator:2.6
    - git:4.8.1
    - job-dsl:1.77
    - sonar-quality-gates:1.3.1
    - maven-plugin:3.12
    - docker-plugin:1.2.3
    - kubernetes:1.30.1
  numExecutors: 1